from django.urls import path, include
from . import views
from .views import cart_page, add_to_cart, remove_from_cart, download_contract

urlpatterns = [
    path('', views.start, name='start_page'),
    path('map/', views.map, name='map_page'),
    path('hottours/', views.hottours, name='hottours_page'),
    path('registration/', views.RegisterView.as_view(), name='registration_page'),
    path('authorization/', views.LoginUserView.as_view(), name='login_page'),
    path('cart/', views.cart_page, name='cart_page'),
    path('cart/<int:tour_id>/', views.cart_page, name='cart_page'),
    path('profile/', views.profile, name='profile_page'),
    path('editprofile/', views.editprofile, name='editprofile_page'),
    path('tours/', views.tours, name='tours_page'),
    path('hotels/', views.hotels, name='hotels_page'),
    path('sales/', views.sales, name='sales_page'),
    path('countries/', views.countries, name='countries_page'),
    path('accounts/', include("django.contrib.auth.urls")),
    path("logout/", views.logout_view, name="logout"),
    path("orderaccept/", views.orderaccept, name="orderaccept_page"),
    path("ordercomplete/", views.ordercomplete, name="ordercomplete_page"),
    path("contracts/", views.contracts, name="contracts_page"),
    path('download_contract/<int:contract_id>/', download_contract, name='download_contract'),
    path('upload-avatar/', views.upload_avatar, name='upload_avatar'),
    path('clearcart/', views.clear_cart, name='clear_cart'),
    path('add_to_cart/<int:tour_id>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:tour_id>/', remove_from_cart, name='remove_from_cart'),
    path("process_payment/", views.process_payment, name="process_payment"),
    path('create-booking/', views.create_booking, name='create_booking'),
    path('cancel-booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    path('create-tour/', views.create_tour, name='create_tour'),
    path('ajax/load-hotels/', views.load_hotels, name='ajax_load_hotels'),
    # path('cart/remove/', views.remove_item, name='remove_item'),
    # path('create_transaction/', views.create_transaction, name='create_transaction'),
    # path('payment_result/<int:transaction_id>/', views.payment_result, name='payment_result'),
]