# Generated by Django 5.1.6 on 2025-02-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/countryphotos/', verbose_name='Фото отеля'),
        ),
    ]
