# Generated by Django 5.1.6 on 2025-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction_clients_passport_data_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/', verbose_name='Фото отеля'),
        ),
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/', verbose_name='Фото тура'),
        ),
    ]
