# Generated by Django 5.1.6 on 2025-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_country_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/countryphotos/', verbose_name='Фото страны'),
        ),
    ]
