# Generated by Django 5.1.6 on 2025-02-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tour_old_price_alter_country_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
