# Generated by Django 5.1.6 on 2025-02-14 11:38

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_tour_departure_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='passport_data',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='passport_data',
            field=models.CharField(max_length=50, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
