# Generated by Django 5.1.6 on 2025-02-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_clients_address_remove_clients_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='password2',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
