# Generated by Django 5.1.6 on 2025-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
