# Generated by Django 5.1.6 on 2025-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_country_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(max_length=250, null=True, unique=True),
        ),
    ]
