# Generated by Django 5.1.6 on 2025-02-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_buyer_address_buyer_date_of_birth_and_more'),
        ('main', '0007_remove_buyer_password1_remove_buyer_password2_and_more'),
    ]

    operations = [
    ]
