# Generated by Django 5.1.6 on 2025-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_country_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='main/profilephotos/', verbose_name='Фото профиля'),
        ),
    ]
