# Generated by Django 5.1.6 on 2025-04-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_booking_options_booking_check_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='booking_price',
        ),
    ]
