# Generated by Django 5.1.6 on 2025-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_booking_price_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Особый пользователь'),
        ),
    ]
