# Generated by Django 5.1.6 on 2025-04-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_buyer_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contracts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='main.contracts'),
        ),
    ]
