# Generated by Django 5.1.6 on 2025-04-24 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_transaction_contracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='contracts',
        ),
        migrations.AddField(
            model_name='contracts',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='main.transaction'),
        ),
    ]
