# Generated by Django 5.1.6 on 2025-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_transaction_contracts_contracts_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
