# Generated by Django 5.1.6 on 2025-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contracts_payment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='is_booking',
            field=models.BooleanField(default=False, verbose_name='Бронирование'),
        ),
    ]
